### ISSUE TITLE
Multiroot workspace sample

### ISSUE THREAD

**Issue by lorenzomar** [elixir-lsp/vscode-elixir-ls#313]
Hello, could you please provide a working sample for a multiroot workspace configuration inside a devcontainer?

This is my setup but it doesn't work:
```
/
┣ .devcontainer/
┃ ┗ devcontainer.json
┃ ┗ docker-compose.yaml
┃ ┗ Dockerfile
┣ .vscode/
┃ ┗ settings.json
┣ package-a/
┃ ┗ mix.exs
┣ package-b/
┃ ┗ mix.exs
┗ project.code-workspace
```

`devcontainer.json`:
```
{
	"name": "myapp",
	"dockerComposeFile": "docker-compose.yml",

	"service": "myapp",
	"workspaceFolder": "/workspace",
	"customizations": {
		"vscode": {
			"extensions": [
				"ms-azuretools.vscode-docker",
				"JakeBecker.elixir-ls"
			]
		}
	}
}
```

`docker-compose.yml`:
```
version: "3.8"

services:
  myapp:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: myapp
    security_opt:
      - seccomp:unconfined
    working_dir: /workspace
    command: tail -f /dev/null
    volumes:
      - ..:/workspace
```

`Dockerfile`:
```
FROM elixir:1.14.3-otp-24
```

---

`settings.json`
```
{
    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/CVS": true,
        "**/.DS_Store": true,
        "**/Thumbs.db": true,
        "**/package-a": true,
        "**/package-b": true
    }
}
```

---

`project.code-workspace`:
```
{
    "folders": [
      { "path": "./", "name": "root" },
      { "path": "./package-a", "name": "package-a" },
      { "path": "./package-b", "name": "package-b" }
    ]
  }
```

Unfortunately this setup doesn't seem to work. When I open workspace in devcontainer extension creates a folder `.elixir_ls` in the root... Am I doing something wrong?

Thanks in advacne for your precious support!
